2023-04-03 02:20:09.274033: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-03 02:20:17.374393: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/home/mcy/conus2_ml/train3fss.py", line 507, in <module>
    history = model.fit(Xdata_train,Ydata_train,epochs=nepochs,\
  File "/home/mcy/mambaforge/envs/tf_gpu/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/__autograph_generated_filel7dg89hd.py", line 15, in tf__train_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
  File "/tmp/__autograph_generated_fileibpeoccn.py", line 19, in tf__loss
    smoothed_target_tensor = ag__.converted_call(ag__.ld(K).conv2d, (), dict(x=ag__.ld(target_tensor), kernel=ag__.ld(weight_matrix), padding='same', strides=(1, 1), data_format='channels_last'), fscope)
ValueError: in user code:

    File "/home/mcy/mambaforge/envs/tf_gpu/lib/python3.9/site-packages/keras/engine/training.py", line 1249, in train_function  *
        return step_function(self, iterator)
    File "/home/mcy/conus2_ml/custom_model_elements.py", line 184, in loss  *
        smoothed_target_tensor = K.conv2d(
    File "/home/mcy/mambaforge/envs/tf_gpu/lib/python3.9/site-packages/keras/backend.py", line 6042, in conv2d
        x = tf.compat.v1.nn.convolution(

    ValueError: Shape must be rank 4 but is rank 3 for '{{node loss/convolution}} = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], explicit_paddings=[], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true](IteratorGetNext:1, loss/convolution_internal/filters)' with input shapes: [?,256,256], [3,3,1,1].

slurmstepd: error: acct_gather_profile/influxdb _send_data: curl_easy_perform failed to send data (discarded). Reason: Couldn't resolve host name
